apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 5e13ad26964d08b20ad6c30637650a723859039ca2b60906dc5dca4b60f606bc
    cni.projectcalico.org/podIP: 192.168.0.26/32
    cni.projectcalico.org/podIPs: 192.168.0.26/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.26"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.26"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-18T19:05:04Z"
  generateName: klum-6b459c87cd-
  labels:
    pod-template-hash: 6b459c87cd
    run: klum
  name: klum-6b459c87cd-rjf2f
  namespace: klum
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: klum-6b459c87cd
    uid: ab363ae1-3eb8-4fab-a005-a13f39a4d465
spec:
  containers:
  - image: ibuildthecloud/klum:v0.1.0-amd64
    imagePullPolicy: IfNotPresent
    name: klum
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-kdcbc
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: klum
  serviceAccountName: klum
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-kdcbc
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
