apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-02-01T16:00:00Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.policy
spec:
  group: policy
  groupPriorityMinimum: 17100
  version: v1
  versionPriority: 15
