apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"kube-rbac-proxy","app.kubernetes.io/created-by":"cerebrum","app.kubernetes.io/instance":"metrics-reader","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"clusterrole","app.kubernetes.io/part-of":"cerebrum"},"name":"cerebrum-metrics-reader"},"rules":[{"nonResourceURLs":["/metrics"],"verbs":["get"]}]}
  creationTimestamp: "2024-02-12T11:59:01Z"
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cerebrum
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: cerebrum
  name: cerebrum-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
