apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"kube-rbac-proxy","app.kubernetes.io/created-by":"cerebrum","app.kubernetes.io/instance":"proxy-rolebinding","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"clusterrolebinding","app.kubernetes.io/part-of":"cerebrum"},"name":"cerebrum-proxy-rolebinding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cerebrum-proxy-role"},"subjects":[{"kind":"ServiceAccount","name":"cerebrum-controller-manager","namespace":"cerebrum-system"}]}
  creationTimestamp: "2024-02-12T11:59:01Z"
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cerebrum
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: cerebrum
  name: cerebrum-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cerebrum-proxy-role
subjects:
- kind: ServiceAccount
  name: cerebrum-controller-manager
  namespace: cerebrum-system
