apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/7xUUW/TQAz+K8jPoawwsSYSD2gICSEhNLa9IB6cO6c9erk7nX0d05T/ji5p2o21XZ54i3325+9zbD8ABnNLkY13UGWD/gi5bPJsveCZ8W82cyhgbZyGCi4Ti2+viH2Kij5RY5yRnFtAS4IaBaF6AHTOC+YHzqavf5MSJplF42cKRSxlZJMhoTj67u8cxdfLzfo4teLVV+P0hxO8ToM7bAkqSEyRZ2ub2n3EpFwOqDIAdAWoSL3ma9MSC7YBKpesLcBiTfZkJ1bIK6jgoqyp1ueNunhbnl28P9f1QpVNUy5KbBYl6jnWqjw7m+dqp5h3BXAglSsuo08BKnimrWefI7a/9oYpQgHBpoh2BIYC2Lhlshi3rowdIjHFDd24tfN37rMhqxmqBi1TAax8yMwubWLpMTfDgDFUPx9G3ps52rDCPFusVtT2c+MDuY/fv9y++7FzhegDRTED11HVU68aKl15O9hGqO0/cvuxtgSVxEQFyH3PjCUat+ybeDgAY8T7/E4uv+oTWLX3ltDl4Pis/lGa08jt52tCdJwG2+08wyy+3IVDGSwo6ZBE77TZ7f2RPlhkuY7o2IzbMklgTrsJGoUmp7TEjMuJ/SPkfAQnhO7Vvxg6OP7LXzno6fdUjxAsPvb92JqpjtuTOWzXqKvrul9PdKJSFIT0t3+OxuOD0Z/AR/9/uH25JOnb3QXI3q77GwAA//8J3B7keAYAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: apiextensions.k8s.io/v1, Kind=CustomResourceDefinition
    objectset.rio.cattle.io/owner-name: users.klum.cattle.io
    objectset.rio.cattle.io/owner-namespace: ""
  creationTimestamp: "2024-02-18T19:05:09Z"
  labels:
    objectset.rio.cattle.io/hash: 79bebd4fc7290764db8c9ff989af89ad1abc9001
  name: users.klum.cattle.io
spec:
  conversion:
    strategy: None
  group: klum.cattle.io
  names:
    kind: User
    listKind: UserList
    plural: users
    singular: user
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              clusterRoles:
                items:
                  nullable: true
                  type: string
                nullable: true
                type: array
              enabled:
                nullable: true
                type: boolean
              roles:
                items:
                  properties:
                    clusterRole:
                      nullable: true
                      type: string
                    namespace:
                      nullable: true
                      type: string
                    role:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      nullable: true
                      type: string
                    lastUpdateTime:
                      nullable: true
                      type: string
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    type:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
