apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"labels":{"app":"gitea"},"name":"gitea-shared-storage-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"10Gi"},"hostPath":{"path":"/tmp/"},"persistentVolumeReclaimPolicy":"Retain","storageClassName":""}}
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-02-14T05:47:50Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    app: gitea
  name: gitea-shared-storage-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitea-shared-storage
    namespace: gitea
    resourceVersion: "2157202"
    uid: 0393d0a7-85fb-46ee-9ef3-f64ff8c36867
  hostPath:
    path: /tmp/
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
