apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  annotations:
    conversion.spec.BondInterfaceConfigs: "null"
    conversion.spec.dpdk.smartnicConfig: '{}'
    conversion.spec.terminationGracePeriodSeconds: "60"
  creationTimestamp: "2024-02-12T12:42:45Z"
  labels:
    crpd.cerebrum.juniper.net/crpd: crpd1-0
    crpd.cerebrum.juniper.net/crpdNamespace: testing
  name: contrail-vrouter-abhi-master-node
  namespace: contrail
spec:
  agent:
    agentTestFramework:
      ksocketDir: /tmp
    controlNode: {}
    crypt: {}
    default:
      agentBaseDirectory: /var/lib/contrail
      coreDumpFilter: "0x13"
      flowCacheTimeout: 0
      grpcServerPort: 50052
      httpServerIp: 0.0.0.0
      httpServerPort: 8085
      logFile: /var/log/contrail/contrail-vrouter-agent.log
      logLevel: SYS_INFO
      mirrorClientPort: 8097
      pkt0TxBuffers: 1000
      restPort: 9091
      sandeshSendRateLimit: 0
      staleInterfaceCleanupTimeout: 60
      syslogFacility: LOG_LOCAL0
      tunnelType: MPLSoGRE
      vmiVMVnUveInterval: 30
      vrObjectHighWatermark: 80
      xmppAuthEnable: false
      xmppCaCert: /etc/contrail/ssl/certs/ca-cert.pem
      xmppServerCert: /etc/contrail/ssl/certs/server.pem
      xmppServerKey: /etc/contrail/ssl/private/server-privkey.pem
    dns:
      dnsClientPort: 8098
      dnsMaxRetries: 2
      dnsTimeout: 3000
    flows:
      fabricSnatHashTableSize: 4096
      flowsAddTokens: 50
      flowsDelTokens: 16
      flowsThreadCount: 1
      flowsUpdateTokens: 16
      indexSmLogCount: 0
      ksyncTokens: 25
      latencyLimit: 0
      maxAggSessionsPerEndpoint: 8
      maxEndpointsPerSessionMsg: 5
      maxSessionsPerAggregate: 100
      maxSystemLinklocalFlows: 2048
      maxVmFlows: 100
      maxVmLinklocalFlows: 2048
      traceEnable: true
    hypervisor:
      hypervisorType: kvm
      vmwareMode: esxi_neutron
    llgr:
      configFallbackTime: 900
      configInactivityTime: 15
      configPollTime: 5
      endOfRibRxFallbackTime: 60
      endOfRibTxFallbackTime: 60
      endOfRibTxInactivityTime: 15
      endOfRibTxPollTime: 5
      staleConfigCleanupTime: 100
    macLearning:
      macLearningAddTokens: 256
      macLearningDelTokens: 256
      macLearningThreadCount: 1
      macLearningUpdateTokens: 256
    metadata:
      metadataClientCertType: PEM
      metadataProxyPort: 8097
    nexthopServer: {}
    qos:
      priorityTagging: true
    restart:
      backupCount: 2
      backupDir: /var/lib/contrail/backup
      backupIdleTimeout: 10000
      restoreAuditTimeout: 15000
      restoreEnable: true
    sandesh:
      introspectSslEnable: false
      sandeshCaCert: /etc/contrail/ssl/certs/ca-cert.pem
      sandeshCertfile: /etc/contrail/ssl/certs/server.pem
      sandeshKeyfile: /etc/contrail/ssl/private/server-privkey.pem
      sandeshSslEnable: false
    serviceInstance:
      netnsTimeout: 0
      netnsWorkers: 0
    services:
      queueLimit: 1024
    session:
      sampleDestination:
      - collector
      sloDestination:
      - collector
    stats: {}
    task:
      logExecThreshold: 0
      logScheduleThreshold: 0
      taskThreadCount: 8
      tbbKeepawakeTimeout: 20000
    traceBuffSize: {}
    virtualHostInterface: {}
  agentModeType: dpdk
  cni:
    vifType: veth
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - abhi-master-node
    containers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-agent:R23.4-95
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          host: 127.0.0.1
          path: /vrouter-health-check
          port: 9091
        initialDelaySeconds: 10
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 5
      name: contrail-vrouter-agent
      resources: {}
      startupProbe:
        failureThreshold: 3
        httpGet:
          host: 127.0.0.1
          path: /vrouter-health-check
          port: 9091
        initialDelaySeconds: 10
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 5
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-dpdk:R23.4-95
      imagePullPolicy: IfNotPresent
      name: contrail-vrouter-agent-dpdk
      resources:
        limits:
          hugepages-1Gi: 6Gi
          memory: 6Gi
        requests:
          hugepages-1Gi: 6Gi
          memory: 6Gi
    - env:
      - name: TELEMETRY_EXPORTER_SCHEME
        value: http
      image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/x86_64/contrail-telemetry-exporter:R23.4-95
      imagePullPolicy: IfNotPresent
      name: contrail-vrouter-telemetry-exporter
      resources: {}
    initContainers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/x86_64/contrail-init:R23.4-95
      imagePullPolicy: IfNotPresent
      name: contrail-init
      resources: {}
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/x86_64/contrail-vrouter-kernel-init-dpdk:R23.4-95
      imagePullPolicy: IfNotPresent
      name: contrail-vrouter-kernel-init-dpdk
      resources: {}
  controlNodeInstance: contrail-control
  coreFilePath: /var/crashes
  corePattern: /var/crashes/core.%e.%h.%t
  dpdk:
    cpuCoreMask: 2,3
    dpdkCommandAdditionalArgs: --yield_option 0
    dpdkUioDriver: uio_pci_generic
    hugePagesDir: /dev/hugepages
    l2TableAgeout: 60
    l2TableSize: "10240"
    mtu: 9000
    numServiceCtrlThreadCPU: 0
  headlessMode: true
  installCni: false
  interfaceLayer: l3
  interfaces:
  - ddp: auto
    level: l3
    name: ens4
    type: fabric
  kernel:
    vifBridgeEntries: 1024
    vifBridgeOEntries: 512
    vrFlowHoldLimit: 8192
    vrInterfaces: 1048576
  logPath: /var/log/jcnr/
  metricsBindAddress: 127.0.0.1:18084
  qosEnable: false
  restoreInterfaces: false
  sriovLabelSelector: {}
  stormControlProfiles:
    rate_limit_pf1:
      bandwidth: {}
  vCommon:
    VrVrfs: 4096
    vrBridgeEntries: 262144
    vrFlowEntries: 524288
    vrMplsLabels: 5120
    vrNexthops: 524288
