apiVersion: crpd.cerebrum.juniper.net/v1
kind: Crpd
metadata:
  creationTimestamp: "2024-02-12T12:42:41Z"
  finalizers:
  - crpd.finalizers.core.cerebrum.juniper.net
  labels:
    cerebrum.juniper.net/instanceSelector: crpd1-0
    cerebrum.juniper.net/instanceType: Crpd
    crpd.cerebrum.juniper.net/crpdGroup: crpd1
  name: crpd1-0
  namespace: testing
  ownerReferences:
  - apiVersion: crpd.cerebrum.juniper.net/v1
    blockOwnerDeletion: true
    controller: true
    kind: CrpdGroup
    name: crpd1
    uid: 9fd53f6c-8f77-4d8d-9cca-c65eb181f889
spec:
  image: svl-artifactory.juniper.net/junos-docker-local/warthog/amd64/crpd:23.4R1.9
  initImage: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/cerebrum-crpd-init:61678478c2
  interfaces:
  - ^ens4$
  - ^ens5$
  - ^eth0$
  vrouter:
    dpdkUioDriver: uio_pci_generic
    imageRepository: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/x86_64
    imageTag: R23.4-95
