apiVersion: core.cerebrum.juniper.net/v1
kind: Interface
metadata:
  creationTimestamp: "2024-02-12T12:42:42Z"
  labels:
    cerebrum.juniper.net/instanceSelector: crpd1-0
    cerebrum.juniper.net/instanceType: Crpd
    cerebrum.juniper.net/interfaceGroup: crpd1-lo0
    cerebrum.juniper.net/interfaceName: lo0
    cerebrum.juniper.net/loopback: "true"
  name: crpd1-0-lo0
  namespace: testing
  ownerReferences:
  - apiVersion: crpd.cerebrum.juniper.net/v1
    kind: Crpd
    name: crpd1-0
    uid: 5d0dfc90-e639-4125-9eaa-62d6d449c206
  - apiVersion: core.cerebrum.juniper.net/v1
    blockOwnerDeletion: true
    controller: true
    kind: InterfaceGroup
    name: crpd1-lo0
    uid: ef03bc21-6d7c-469e-98a2-254901eb5567
spec:
  families:
  - addressFamily: inet
    ipAddress: 12.12.0.1/32
  instanceParent:
    parentType: crpdGroup
    reference:
      apiVersion: crpd.cerebrum.juniper.net/v1
      kind: CrpdGroup
      name: crpd1
      namespace: testing
      uid: 9fd53f6c-8f77-4d8d-9cca-c65eb181f889
  interfaceName: lo0
  managed: true
  mtu: 9216
