apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-01T16:00:18Z"
  generateName: kube-multus-ds-
  labels:
    app: multus
    controller-revision-hash: 5f7749fc79
    name: multus
    pod-template-generation: "1"
    tier: node
  name: kube-multus-ds-8mkkk
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-multus-ds
    uid: 325d29df-ad2a-41df-8605-999b3de9da43
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - abhi-master-node
  containers:
  - args:
    - --multus-conf-file=auto
    - --cni-version=0.3.1
    command:
    - /entrypoint.sh
    image: ghcr.io/k8snetworkplumbingwg/multus-cni:v3.9.2
    imagePullPolicy: IfNotPresent
    name: kube-multus
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/etc/cni/net.d
      name: cni
    - mountPath: /host/opt/cni/bin
      name: cnibin
    - mountPath: /tmp/multus-conf
      name: multus-cfg
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rchxb
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: abhi-master-node
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: multus
  serviceAccountName: multus
  terminationGracePeriodSeconds: 10
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: cnibin
  - configMap:
      defaultMode: 420
      items:
      - key: cni-conf.json
        path: 70-multus.conf
      name: multus-cni-config
    name: multus-cfg
  - name: kube-api-access-rchxb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
