apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 70b75d3bd71b69823d97d4eb403528f156f5c895149af8afed61ddf46fddb1c4
    cni.projectcalico.org/podIP: 192.168.0.49/32
    cni.projectcalico.org/podIPs: 192.168.0.49/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.49"
          ],
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "192.168.0.49"
          ],
          "default": true,
          "dns": {}
      }]
  creationTimestamp: "2024-02-01T16:13:21Z"
  generateName: calico-kube-controllers-575997b95b-
  labels:
    k8s-app: calico-kube-controllers
    pod-template-hash: 575997b95b
  name: calico-kube-controllers-575997b95b-gj92x
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: calico-kube-controllers-575997b95b
    uid: 1ba2619c-7110-4933-833a-e4c2fbf005ce
spec:
  containers:
  - env:
    - name: ENABLED_CONTROLLERS
      value: node
    - name: DATASTORE_TYPE
      value: kubernetes
    image: svl-artifactory.juniper.net/atom_virtual_docker/calico/kube-controllers:v3.26.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /usr/bin/check-status
        - -l
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: calico-kube-controllers
    readinessProbe:
      exec:
        command:
        - /usr/bin/check-status
        - -r
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-74xll
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: abhi-master-node
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: calico-kube-controllers
  serviceAccountName: calico-kube-controllers
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-74xll
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
