apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"Issuer","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"certificate","app.kubernetes.io/created-by":"cerebrum","app.kubernetes.io/instance":"serving-cert","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"certificate","app.kubernetes.io/part-of":"cerebrum"},"name":"cerebrum-selfsigned-issuer","namespace":"cerebrum-system"},"spec":{"selfSigned":{}}}
  creationTimestamp: "2024-02-12T11:59:01Z"
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: cerebrum
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: cerebrum
  name: cerebrum-selfsigned-issuer
  namespace: cerebrum-system
spec:
  selfSigned: {}
