apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"metallb"},"name":"controller","namespace":"metallb-system"}}
  creationTimestamp: "2024-02-01T16:12:12Z"
  labels:
    app: metallb
  name: controller
  namespace: metallb-system
